-- ============================================================================
-- DEPRECATED: This file is no longer used
-- USE: AUTHORITATIVE_SCHEMA.sql in the repository root instead
-- 
-- This file was kept for reference but should not be used for deployment
-- The AUTHORITATIVE_SCHEMA.sql contains the complete, production-ready schema
-- ============================================================================
