name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component Type
      description: What type of component is affected?
      options:
        - Datapack
        - Plugin
        - AMP Configuration
        - Server Template
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: component-name
    attributes:
      label: Component Name
      description: What specific component is affected?
      placeholder: ex. Terralith v2.5.11, BentoBox plugin, Hetzner config
    validations:
      required: true

  - type: dropdown
    id: server-type
    attributes:
      label: Server Type
      description: What type of server are you running?
      options:
        - Hetzner
        - OVH
        - Local Development
        - Other Hosting Provider
        - Not Server Specific
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - 1.21.x
        - 1.20.x
        - 1.19.x
        - Other
    validations:
      required: false

  - type: dropdown
    id: amp-version
    attributes:
      label: AMP Version
      description: What version of AMP are you using?
      options:
        - 2.5.x
        - 2.4.x
        - 2.3.x
        - Other
        - Not using AMP
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: What steps did you take that led to this issue?
      placeholder: |
        1. Navigate to '...'
        2. Install '...'
        3. Configure '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: Describe what you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched for existing issues that might be related to this bug
          required: true
        - label: I have provided all relevant information including versions and configuration details
          required: true
        - label: I have tested this in a clean environment to rule out conflicts with other modifications
          required: false
        - label: I have included log output or error messages (if applicable)
          required: false
