name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! We appreciate your input.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Datapack Addition
        - New Plugin Addition
        - Configuration Enhancement
        - New Server Template
        - Documentation Improvement
        - Tool/Script Addition
        - Repository Structure Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my current workflow
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe what problem this would solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches could include...
    validations:
      required: false

  - type: dropdown
    id: compatibility
    attributes:
      label: Compatibility Requirements
      description: What versions should this feature support?
      multiple: true
      options:
        - Minecraft 1.21.x
        - Minecraft 1.20.x
        - Minecraft 1.19.x
        - AMP 2.5.x
        - AMP 2.4.x
        - AMP 2.3.x
        - All Server Types
        - Hetzner Only
        - OVH Only
        - No Specific Requirements
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature. How would you use it?
      placeholder: I would use this feature to...
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: If you have ideas about how this could be implemented, please share them.
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: What kind of impact would this feature have?
      options:
        - Performance Improvement
        - Ease of Use Enhancement
        - New Functionality
        - Better Documentation
        - Maintenance Improvement
        - Security Enhancement
        - Other
    validations:
      required: false

  - type: textarea
    id: resources
    attributes:
      label: Resources/References
      description: |
        Please provide links to any relevant resources, documentation, or examples.
        
        For datapack/plugin requests, include:
        - Official download links
        - Documentation links
        - Version compatibility information
        - License information
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I can provide testing for this feature
        - label: I can help with documentation for this feature
        - label: I can provide the necessary resources (datapacks, plugins, etc.)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or examples about the feature request here.
        
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you have completed these steps
      options:
        - label: I have searched for existing feature requests that might be similar to this one
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I have considered the compatibility implications of this feature
          required: true
        - label: For datapack/plugin requests, I have verified the source is reputable and actively maintained
          required: false
